version: '3'
services:
  node-app:
    build: .
    container_name: node-express
    ports:
      - 3000:3000  
    volumes:
      - /app/node_modules 
      - .:/app 
    environment:
      -  PORT=3000
    # env_file:
    #   - ./.env

